// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Unit-test names don't have to follow naming style")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.LocalPackageDetailControlModelTests.#ctor(Microsoft.VisualStudio.Sdk.TestFramework.GlobalServiceProvider,NuGet.Test.Utility.LocalPackageSearchMetadataFixture)")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.LocalPackageSolutionDetailControlModelTests.#ctor(Microsoft.VisualStudio.Sdk.TestFramework.GlobalServiceProvider,NuGet.Test.Utility.LocalPackageSearchMetadataFixture)")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.V3PackageDetailControlModelTests.#ctor(Microsoft.VisualStudio.Sdk.TestFramework.GlobalServiceProvider,NuGet.Test.Utility.V3PackageSearchMetadataFixture)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.V3PackageDetailControlModelTests.WhenPackageStyleIsNotPackageReference_And_CustomVersion_BrowseTab_IsSelectedVersionCorrect(NuGet.VisualStudio.Internal.Contracts.NuGetProjectKind,NuGet.ProjectModel.ProjectStyle,System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.V3PackageDetailControlModelTests.WhenPackageStyleIsNotPackageReference_And_CustomVersion_InstalledTab_IsSelectedVersionCorrect(NuGet.VisualStudio.Internal.Contracts.NuGetProjectKind,NuGet.ProjectModel.ProjectStyle,System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.V3PackageDetailControlModelTests.WhenPackageStyleIsNotPackageReference_And_CustomVersion_UpdatesTab_IsSelectedVersionCorrect(NuGet.VisualStudio.Internal.Contracts.NuGetProjectKind,NuGet.ProjectModel.ProjectStyle,System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.V3PackageDetailControlModelTests.WhenPackageStyleIsPackageReference_And_CustomVersion_BrowseTab_IsSelectedVersionCorrect(System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.V3PackageDetailControlModelTests.WhenPackageStyleIsPackageReference_And_CustomVersion_InstalledTab_IsSelectedVersionCorrect(System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.Models.V3PackageDetailControlModelTests.WhenPackageStyleIsPackageReference_And_CustomVersion_UpdatesTab_IsSelectedVersionCorrect(System.String,System.String,System.Boolean,System.Boolean)")]
[assembly: SuppressMessage("Usage", "VSTHRD002:Avoid problematic synchronous waits", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.WpfTestCase.CopyTaskResultFrom``1(System.Threading.Tasks.TaskCompletionSource{``0},System.Threading.Tasks.Task{``0})")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.PackageManagement.UI.Test.WpfTestCase.RunAsync(Xunit.Abstractions.IMessageSink,Xunit.Sdk.IMessageBus,System.Object[],Xunit.Sdk.ExceptionAggregator,System.Threading.CancellationTokenSource)~System.Threading.Tasks.Task{Xunit.Sdk.RunSummary}")]
