// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.VisualStudio.Threading.Analyzers", "VSTHRD010", Justification = "Test code does not need to follow this rule.")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.RestoreOperationLoggerTests.StatusBarProgress_StartAsync_CancellationTokenThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD012:Provide JoinableTaskFactory where allowed", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.NominateProjectAsync(System.String,NuGet.SolutionRestoreManager.IVsProjectRestoreInfo,System.Threading.CancellationToken,Moq.Mock{NuGet.VisualStudio.IProjectSystemCache},Moq.Mock{NuGet.VisualStudio.ISolutionRestoreWorker},Moq.Mock{NuGet.Common.ILogger})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD012:Provide JoinableTaskFactory where allowed", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.NominateProjectAsync(System.String,NuGet.SolutionRestoreManager.IVsProjectRestoreInfo2,System.Threading.CancellationToken,Moq.Mock{NuGet.VisualStudio.IProjectSystemCache},Moq.Mock{NuGet.VisualStudio.ISolutionRestoreWorker},Moq.Mock{NuGet.Common.ILogger})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD012:Provide JoinableTaskFactory where allowed", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.NominateProjectAsync_PackageDownload_InexactVersionsNotAllowed~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD012:Provide JoinableTaskFactory where allowed", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.NominateProjectAsync_PRI2_WithDifferentPackageVersions_Fails(System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD012:Provide JoinableTaskFactory where allowed", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.NominateProjectAsync_ThrowsNullReferenceException")]
[assembly: SuppressMessage("Usage", "VSTHRD012:Provide JoinableTaskFactory where allowed", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.NominateProjectAsync_WithDifferentPackageVersions_Fails(System.String,System.String)~System.Threading.Tasks.Task")]
