// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.DescriptionAnalyzer.TokenStream(System.String,System.IO.TextReader)~Lucene.Net.Analysis.TokenStream")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.DownloadCountResultsIndexer.ProcessUnrankedEntries(System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.IPackageSearchMetadata},System.Collections.Generic.IDictionary{System.String,System.Int64})~System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.IPackageSearchMetadata}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.IdentifierAnalyzer.TokenStream(System.String,System.IO.TextReader)~Lucene.Net.Analysis.TokenStream")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.IdentifierKeywordAnalyzer.TokenStream(System.String,System.IO.TextReader)~Lucene.Net.Analysis.TokenStream")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.NuGetQuery.ConstructQuery(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.HashSet{System.String}})~Lucene.Net.Search.Query")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.NuGetQuery.MakeQuery(System.String)~Lucene.Net.Search.Query")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.OwnerAnalyzer.TokenStream(System.String,System.IO.TextReader)~Lucene.Net.Analysis.TokenStream")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.PackageAnalyzer.#ctor")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.RelevanceSearchResultsIndexer.ProcessUnrankedEntries(System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.IPackageSearchMetadata},System.Collections.Generic.IDictionary{System.String,System.Int64})~System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.IPackageSearchMetadata}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.SearchResultsAggregator.AggregateAsync(System.String,System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.IPackageSearchMetadata}[])~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{NuGet.Protocol.Core.Types.IPackageSearchMetadata}}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.TagsAnalyzer.TokenStream(System.String,System.IO.TextReader)~Lucene.Net.Analysis.TokenStream")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.TokenizingHelper.CamelCaseSplit(System.String)~System.Collections.Generic.IEnumerable{System.String}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Indexing.VersionAnalyzer.TokenStream(System.String,System.IO.TextReader)~Lucene.Net.Analysis.TokenStream")]
